version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=5000
    command: npm run start

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
